### ISSUE TITLE
ShortCuts Not working

### ISSUE THREAD

**Issue by nickwild-999** [kevinjalbert/todoist-shortcuts-nativefier#4]
Not sure if this project is still being maintained, but this does not work. 

App builds and loads OK but no shortcuts :-(

**Comment by nickwild-999** [comment]
Just seen the todoist-shortcuts. Changed locally to 61 and all works.
Will submit a PR to update

**Comment by kevinjalbert** [comment]
Closing this issue out as the `todoist-shortcuts` aspect has been updated to the latest as of today.
